### ISSUE TITLE
test note

### ISSUE THREAD

**Issue by Hearthstowner** [IMB-a/miet_union#12]
Как автоматизировать breadcrumbs имея только django request?
Пытался через request.path, пока не получилось.

**Comment by TheNooBest** [comment]
( ★)7

**Comment by Hearthstowner** [comment]
Пробовал использовать reverse() для получения полного url, дальше не знаю что делать.

**Comment by Hearthstowner** [comment]
Решил проблему через templatetags:
# ..._extras.py

@register.filter()
def get_path_names(request):
    valid_path_names = []
    for name in list(filter(None, request.path.strip('/').split('/'))):
        try:
            reverse(name)
        except NoReverseMatch:
            pass
        else:
            valid_path_names.append(name)
    return valid_path_names

#15 base.html

{% breadcrumb 'home' 'home' %}
      {% for path in request|get_path_names %}
      {% breadcrumb path path %}
      {% endfor %}
      {% render_breadcrumbs %}
